//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practika.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authorization
    {
        public string Login { get; set; }
        public string Pass { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> Student_code { get; set; }
        public Nullable<int> Item_number { get; set; }
    
        public virtual Participant Participant { get; set; }
        public virtual Role Role { get; set; }
        public virtual Selection_committee Selection_committee { get; set; }
    }
}
