//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practika.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Occupation_type
    {
        public int Study_type_code { get; set; }
        public string Name { get; set; }
        public Nullable<int> Load_code { get; set; }
    
        public virtual Load Load { get; set; }
    }
}
