//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practika.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int Schedule_code { get; set; }
        public Nullable<System.DateTime> Lesson_time { get; set; }
        public Nullable<int> Audience_code { get; set; }
        public Nullable<int> Group_code { get; set; }
        public Nullable<int> Teacher_code { get; set; }
    
        public virtual Audience Audience { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
