//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practika.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Selection_committee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Selection_committee()
        {
            this.Authorization = new HashSet<Authorization>();
        }
    
        public int Item_number { get; set; }
        public string Full_name { get; set; }
        public Nullable<int> School_code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Authorization> Authorization { get; set; }
        public virtual Educational_institution Educational_institution { get; set; }
    }
}
